name: Build

on:
  pull_request

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
        id: go

      - name: Print Go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

  build_docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag inx-dashboard:latest
